### ISSUE TITLE
CryptographicException with CNG certificate

### ISSUE THREAD

**Issue by starteleport** [ITfoxtec/ITfoxtec.Identity.Saml2#1]
After migrating from @huan086 [fork with CNG support](https://github.com/ITfoxtec/ITfoxtec.SAML2/pull/3) I get `CryptographicException` with message that roughly translates to English like "Invalid provider type" with stack like this

```
   in System.Security.Cryptography.Utils.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
   in System.Security.Cryptography.Utils.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean randomKeyContainer, Int32 dwKeySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
   in System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
   in System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 dwKeySize, CspParameters parameters, Boolean useDefaultKeySize)
   in System.Security.Cryptography.X509Certificates.X509Certificate2.get_PrivateKey()
   in ITfoxtec.Identity.Saml2.Saml2Binding`1.BindInternal(Saml2Request saml2RequestResponse) in C:\Users\baraboshkin_nd\Documents\ITfoxtec.Identity.Saml2\src\ITfoxtec.Identity.Saml2\Bindings\Saml2Binding.cs:line 50
   in ITfoxtec.Identity.Saml2.Saml2RedirectBinding.BindInternal(Saml2Request saml2RequestResponse, String messageName) in C:\Users\baraboshkin_nd\Documents\ITfoxtec.Identity.Saml2\src\ITfoxtec.Identity.Saml2\Bindings\Saml2RedirectBinding.cs:line 25
   in ITfoxtec.Identity.Saml2.Saml2Binding`1.Bind(Saml2Request saml2Request) in  C:\Users\baraboshkin_nd\Documents\ITfoxtec.Identity.Saml2\src\ITfoxtec.Identity.Saml2\Bindings\Saml2Binding.cs:line 32
```

Does this mean it is really somehow related to CNG? If so, do you plan to add support for CNG?

**Comment by huan086** [comment]
It's a built-in limitation of .NET Framework < 4.6.2. My fork uses another library to handle CNG. If I'm not wrong, Microsoft recently added CNG to .NET 4.6.2, which is in preview now.

**Comment by starteleport** [comment]
@huan086, I am ready to re-implement your solution here, if neither you nor @Revsgaard are going to do so. That's my primary question :smiley:

**Comment by huan086** [comment]
Thing is, does .NET 4.6.2 solve the problem? I see it in the changelog that they now support CNG and new algorithms for SignedXml

**Comment by starteleport** [comment]
@huan086, ok, will try

**Comment by Revsgaard** [comment]
Both SHA1 (http://www.w3.org/2000/09/xmldsig#rsa-sha1) and SHA2 (http://www.w3.org/2001/04/xmldsig-more#rsa-sha256) is supported for message signing in this libary from .NET 4.5. I have extended the SignedXml class. SHA2 is the .NET constant SecurityAlgorithms.RsaSha256Signature.

Perhaps SHA2 can be used?

**Comment by starteleport** [comment]
@huan086 I've tried to switch to 4.6.2 without touching code with no luck, will now try to figure out what code modifications are needed to support CNG in this lib starting from 4.5

@Revsgaard the problem is that I use CNG certificate and thus appropriate signature formatter is needed. @huan086, pleasae correct me if I'm wrong.

**Comment by starteleport** [comment]
@huan086 I've tried upgrade to .NET 4.6.2, and it helped only partially. Finally, I've ported your `Security.Cryptography`-related code as it is compatible with older frameworks. @Revsgaard, if you are interested, I can make pull-request for this. Additionally, I've fixed a number of bugs. For some of them I can make independent PRs, some of them need CNG stuff to support new certificates in unit tests.

**Comment by Revsgaard** [comment]
Yes please make pull-requests for the CNG code and bug fixes. I'm especially interested in the bug fixes, but maybe others can benefit by the CNG related code.

**Comment by huan086** [comment]
I think the reason the code didn't work with CNG is due to the call to `.PrivateKey`. Should replace them with `.GetRSAPrivateKey()` instead. See https://www.stum.de/2016/05/19/net-framework-4-6-2-adds-support-to-sign-xml-documents-using-rsa-sha256/

**Comment by Revsgaard** [comment]
Thank you for the contribution.
The project is updated to .NET 4.6.2 and the code is changed to use `.GetRSAPrivateKey()`.
https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/commit/69810b02d52213a7650884ece188af5eb4fc165f
