### ISSUE TITLE
.NET Core 6 support

### ISSUE THREAD

**Issue by Ruud-cb** [ITfoxtec/ITfoxtec.Identity.Saml2#102]
Hi,

Wondering if or when .NET Core 6 is supported, because .NET Core 6 is LTS version and .NET Core 5 is end of support in May.

Thanks

**Comment by Revsgaard** [comment]
Thanks for you message.

Support for .NET 6 is added from version [4.8.0](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/releases/tag/4.8.0).

Regards 
Anders
