### ISSUE TITLE
Signature validation of message with the "&#13;" character sequence

### ISSUE THREAD

**Issue by bdhamelicodra** [ITfoxtec/ITfoxtec.Identity.Saml2#107]
When acting as Service Provider and using PingOne Identity Provider with both assertion and response signature, PingOne adds the certificate used to sign the assertion in the response, this certificate contains the sequence of characters "\&\#13\;".
The .Net Framework classes System.Security.Cryptography.Xml.SignedXml and System.Xml.XmlDocument, seem to remove the character sequence "\&\#13\;" when reading the XML document of the response and failed to verify signature of the message (no problem with the assertion signature).
The signing certificate is provided by PingOne with no configuration options (in particular, removing this character sequence or not including the certificate in the response).

**Comment by Revsgaard** [comment]
Related problem https://support.pingidentity.com/s/question/0D58Z00009EPUbBSAX/i-am-trying-to-use-pingone-saml-idp-but-when-the-assertion-and-response-are-signed-the-sp-fails-to-validate-the-response-signature-due-to-the-presence-of-13-in-the-response

**Comment by Revsgaard** [comment]
Maybe related problem
https://stackoverflow.com/questions/71446457/aws-sso-signature-verification-problems

**Comment by Revsgaard** [comment]
The problem shown in a diff
![image](https://user-images.githubusercontent.com/9498173/167854852-a3f71ab7-dcb6-449b-b1e1-a65455372d3f.png)

**Comment by Revsgaard** [comment]
Eexpect the problem to be solved in .NET 7.
