### ISSUE TITLE
Unable to find SAML Response Attribute

### ISSUE THREAD

**Issue by adriangonzalez** [ITfoxtec/ITfoxtec.Identity.Saml2#109]
First off, thank you all for the time and effort you have put into this project. It is appreciated. Now to the issue :) When getting a SAML response from our IDP, in the XML, there is an attribute called *SessionNotOnOrAfter*. This attribute is providing a  value which is one hour after the initial request. I believe this indicates that the IDP has a session timeout of 1 hour.  Although I am seeing this attribute in the SAML Response XML, I am not seeing a corresponding property in the Saml2AuthnResponse class. Should this attribute translated into a property in the Saml2AuthnResponse class? I apologize if I've misunderstood something here.

![image](https://user-images.githubusercontent.com/1702732/172477592-267e5416-cc6d-4e26-9285-777da72cef09.png)

**Comment by Revsgaard** [comment]
Thanks!
The SessionNotOnOrAfter attribut is currently not supported by the component. Feel free to add support for the attribut in a pull request.

From the SAML 2.0 core standard:

> SessionNotOnOrAfter [Optional]
> Specifies a time instant at which the session between the principal identified by the subject and the
> SAML authority issuing this statement MUST be considered ended. The time value is encoded in
> UTC, as described in Section 1.3.3. There is no required relationship between this attribute and a
> NotOnOrAfter condition attribute that may be present in the assertion.
