### ISSUE TITLE
Port to .Net Standard

### ISSUE THREAD

**Issue by sergiorykov** [ITfoxtec/ITfoxtec.Identity.Saml2#11]
You use crypto stuff from many .Net Framework-only libraries. MS may port them in a year or two^).
Can you switch cryptography/encoding related things to another crypto library with .Net Standard support and issue .Net standard package?

**Comment by Revsgaard** [comment]
No I do not have any planes to use other than .NET crypto libraries. Also I do not know if MS will move the SAML 2.0 stuff used in the package.
