### ISSUE TITLE
How can I Logout all SPs from Idp?

### ISSUE THREAD

**Issue by xiaoyaojian** [ITfoxtec/ITfoxtec.Identity.Saml2#114]
Our root site is asp.net mvc application, and the SP sites is wordpress with miniOrange SP plugin installed, 
My question is how can I logout all SPs from Idp use this library?

**Comment by Revsgaard** [comment]
Yes the library support single logout both as IdP and RP. But the library only support the SAML 2.0 standard, you need to implement the rest of the IdP functionality your self or use an IdP like [FoxIDs](https://foxids.com).

I'll close this issue, please ask your question on stackoverflow and tag it with 'itfoxtec-identity-saml2', and I'll gladly answer.
