### ISSUE TITLE
Signature Validation with Multiple Signatures

### ISSUE THREAD

**Issue by willisd2** [ITfoxtec/ITfoxtec.Identity.Saml2#119]
Been fighting with a problem for a couple of weeks now where I'm getting a  "Signature is invalid" exception when trying to validate a SAML2 Response. From looking at the POSTed response, everything looks kosher. I've tried a handful of ways of providing the Signing Certificate and keep ending up with the same result.

After lots of inheriting/overriding of classes/methods in the ITfoxtec package in order to debug, I found out that the overall document validation seems to be passing just fine, but there is also a signed assertion using the same certificate used to sign the document, that is failing. 

Through some research, I was able to track this down as seemingly a bug in .NET's SignedXml.CheckSignature method. 

**Additional Info:**
https://stackoverflow.com/questions/71446457/aws-sso-signature-verification-problems (StackOverflow of someone else experiencing the same problem using the ITfoxtec SAML implementation)

https://stackoverflow.com/questions/25394137/verify-signature-on-saml-assertion (StackOverflow issue that loosely talks about this CheckSignature issue and offers a workaround)

https://github.com/i8beef/SAML2/blob/master/src/SAML2/Utils/XmlSignatureUtils.cs (Another SAML2 implementation on github that works around this issue and references a page I've seen others on StackOverflow reference that talked about this issue which unfortunately no longer exists, https://support.microsoft.com/en-us/kb/952697)

**Comment by willisd2** [comment]
I'm really not sure what I'm up against here. Through more digging in the source code, it appears that everything is being handled to work around that supposed .NET bug. Current routes of investigation are centered around .NET trying to validate a Java signed Assertion. It just doesn't make sense that the document would pass, which would seemingly include the assertion as part of it, but the individual signed assertion does not pass...

**Comment by willisd2** [comment]
So I ended up setting up a Java development environment and ran my SAML Response through a signature validation. Both the document and assertion validations seemingly passed with flying colors. I also checked the canonicalization output between Java and .NET and everything seemed alright in that regard too. 

This helped narrow my focus to this issue being a .NET signature validation issue. Through some more digging, I found this github issue https://github.com/dotnet/runtime/issues/27500 created by the author of another .NET SAML2 library, that seems to address this exact problem. It looks like the fix will be part of .NET 7. I'm unclear if it's getting ported back to the regular .Net Framework or not. Once .NET 7 is released next month, I should be able to pull it into my project and this will no longer be an issue for me. It could still be an issue for users of your library that aren't on the latest version of .NET, or on versions of the .Net Framework.

**Comment by Revsgaard** [comment]
Thank you for your work and investigation. I'm most gratefully. 
Hopefully the bug fix will be applied for both .NET 7 and older frameworks. Unfortunately we can't do anything but wait and see.

**Comment by willisd2** [comment]
> Thank you for your work and investigation. I'm most gratefully. Hopefully the bug fix will be applied for both .NET 7 and older frameworks. Unfortunately we can't do anything but wait and see.

No problem, glad to be able to help.

I've done a little bit more research over the past few days as well. It turns out we don't have to fully upgrade to .NET 7 to pull in the fix from the other github issue. It's part of the System.Security.Cryptography.Xml NuGet package. I was able to upgrade to a 7.0.0 release candidate version of it, as it doesn't require targeting .NET 7. This alone still didn't solve my issue, but I ended up creating a new class that inherited from the Saml2AuthnResponse class, overrode the GetAssertionElement() method, gave it the same logic that Saml2AuthnResponse.GetAssertionElement() is doing, except on the return value I have it returning the 'assertionElement' directly. Instead of turning it into a new XmlDocument and returning the DocumentElement. By doing that, and using that inherited class instead, my signature checks started passing...

I have no idea on the implications of that change, but I cloned this repository locally so I could try it out and run the unit tests.

**Comment by Revsgaard** [comment]
Okay, thank you for the information. 
Do you prosumer that it is necessary to do the code changes you mentions when updating to System.Security.Cryptography.Xml 7.0.0?

Please add the code changes if possible.

**Comment by Revsgaard** [comment]
Resolved in https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/commit/02eb45e9867f7d60a4dac958670d22729d38c620

**Comment by Revsgaard** [comment]
Released in https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/releases/tag/4.8.3-beta5
