### ISSUE TITLE
The NameIdentifier claim is automatically removed from SAML attributes

### ISSUE THREAD

**Issue by matchab** [ITfoxtec/ITfoxtec.Identity.Saml2#122]
Hello there,

I'm not sure this is an actual issue, but I wonder why the library automatically removes any NameIdentifier claim included in the ClaimsIdentity subject:

https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/blob/f818778eea6a957b59eb30de0a1b62a34731deba/src/ITfoxtec.Identity.Saml2/Request/Saml2AuthnResponse.cs#L141

We have a use case where we specifically need to pass a SAML attribute named `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier`, AKA the NameIdentifier claim (and it needs to be different of the SAML NameId though). Given the current behaviour of the lib, this case is impossible to achieve.

The question is: why is the library doing this? I have searched in the SAML spec and can't find any mention of this rule... So what's the point?

**Comment by Revsgaard** [comment]
You need to overload the Saml2AuthnResponse.CreateTokenDescriptor method to send a NameIdentifier claim beside the NameID in the Subject element.

**Comment by Revsgaard** [comment]
I see the NameIdentifier claim is a representation for the Subject NemID. The Subject NemID is required to do logout. Therefore, to avoid having two different IDs basically on the same level and with the same type - the NameIdentifier claim is filtered away.

**Comment by matchab** [comment]
OK I understand, but the subject of the security token here is totally unrelated with the SAML NameId. I mean:

* The NameId is set via `Saml2Request.NameId`, in which we can put any value (not specifically the NameIdenfifier claim).
* The subject is set via `Saml2AuthnResponse.ClaimsIdentity`, which actually represents the collection of SAML attributes that will be sent to the service.

IMO, there is no reason to filter this claim here, and we should have full control over the SAML attributes we want to send to the service provider.

Let me know if you are okay with this, and I will submit a PR which remove the claim filter soon.

**Comment by Revsgaard** [comment]
You can change the behaver by changing the SecurityTokenDescriptor and calling the CreateSecurityTokenAsyn , an example from FoxIDs
https://github.com/ITfoxtec/FoxIDs/blob/master/src/FoxIDs/Logic/Saml/SamlAuthnDownLogic.cs#L254

You are welcome to submit code. The default action should not change but instead change by setting a property.
