### ISSUE TITLE
Lost headers between original request and authenticated request

### ISSUE THREAD

**Issue by fmaeseele** [ITfoxtec/ITfoxtec.Identity.Saml2#128]
Hi,

In an .aspnet core application, I have an endpoint that requires SAML2 authentication:
/view/metadata
Once I hit this EndPoint from a WebSite using an X-Csrf-Token header, the authentication is triggered to the EndPoint:
/auth/saml/login?returnurl=/view/metadata
But the header X-Csrf-Token is already lost.
Once I authenticate through the IDP, it returns at the end to the original EndPoint:
/view/metadata

But the header X-Csrf-Token is not present.
Generally speaking, any specific header I could send in my query is lost after authenticating.

Also, as an enhancement, I think instead using a SAML Controller that anyone has to implement the same way, it would be better to implement the authentication part into a middleware like other authentication providers. I could helpl if anyone is interested.
It would avoid to use the "returnUrl" trick for example and works like in SpringFramework (java world)

Regards,
François

**Comment by fmaeseele** [comment]
Logs:

1st request:

Request:
Protocol: HTTP/1.1
Method: GET
Scheme: https
PathBase:
Path: /view/metadata
Accept: /
Host: localhost:48443
User-Agent: Test/0.1
Accept-Charset: utf-8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US
X-Csrf-Token: Fetch

Response:
StatusCode: 302
Location: https://localhost:48443/auth/saml/Login?ReturnUrl=%2Fview%2Fmetadata

2nd request:

Request:
Protocol: HTTP/1.1
Method: GET
Scheme: https
PathBase:
Path: /auth/Login
Accept: /
Host: localhost:48443
User-Agent: Test/0.1
Accept-Charset: utf-8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US
Referer: [Redacted]

As you can see, the 2nd request doesn't keep header X-Csrf-Token from 1st query.

**Comment by Revsgaard** [comment]
The /view/metadata endpoint should accept anonymous access and not require authentication. The endpoint is called by other servers and not users/clients.

It is a good idea to implement a middleware supporting default configuration and making it possible to select binding. 
You are welcome to contribute with a pull request.

**Comment by fmaeseele** [comment]
Hi,
Sorry for the wrong example, I should have choosen /view/customers instead of /view/metadata.
So, of course, I was not talking about the ServiceProvider Metadata URL but any secured url instead.

**Comment by Revsgaard** [comment]
It is not possible to transfer HTTP headers in a browser redirect or POST.

When you do a login the browser page should be replaced entirely by doing a redirect or POST. SAML 2.0 do not support any type of rich browser client or to secure an API. If either is used in the application the SAML 2.0 calls is handled before and then some other security mechanism takes over.
