### ISSUE TITLE
Saml Response issue in AssertionConsumerService Method

### ISSUE THREAD

**Issue by vinu28** [ITfoxtec/ITfoxtec.Identity.Saml2#13]
Hello All,

I have implement saml authentication in ADFS.

it is redirecting to ADFS and after login it call the AssertionConsumerService.
but in AssertionConsumerService it is giving error 
There is not exactly one Assertion element.

Below is my saml response:

<saml2p:Response xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" ID="_fdf3be69-187c-4906-ba6f-4e2cd8f0cac6" Version="2.0" IssueInstant="2017-11-01T10:34:25.3123813Z" Destination="https://fs.timesgroup.com/adfs/ls/"><saml2:Issuer>https://azeatoiwebapp1s.azurewebsites.net</saml2:Issuer><saml2p:Status><saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" /></saml2p:Status></saml2p:Response>

Also Please suggest the steps for ADFS configuration and default sp xml to load in ADFS.
please help me..

Thanks & Regards

**Comment by Revsgaard** [comment]
Hi,

The response from AD FS should contain an assertion element if the status is success. I do not know way you AD FS do not return a correct SAML 2.0 response. I'm afraid that I have never seen that problem. Meybe there are a error in the AD FS event log.

Regards Anders
