### ISSUE TITLE
Saml2Configuration is missing the attribute ArtifactResolutionService.

### ISSUE THREAD

**Issue by luozewei** [ITfoxtec/ITfoxtec.Identity.Saml2#132]
Saml2Configuration is missing the attribute ArtifactResolutionService. I saw it in use in TestWebAppCoreArtifact, but the attribute was not found in the actual reference 4.8.2
`    saml2Configuration.AllowedIssuer = entityDescriptor.EntityId;
                    saml2Configuration.SingleSignOnDestination = entityDescriptor.IdPSsoDescriptor.SingleSignOnServices.First().Location;
                    saml2Configuration.SingleLogoutDestination = entityDescriptor.IdPSsoDescriptor.SingleLogoutServices.First().Location;
                    saml2Configuration.ArtifactResolutionService = entityDescriptor.IdPSsoDescriptor.ArtifactResolutionServices.Select(s => new Saml2IndexedEndpoint { Index = s.Index, Location = s.Location }).First();`
Is this attribute invalid?

**Comment by Revsgaard** [comment]
Released in 4.8.4 - https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/releases/tag/4.8.4
