### ISSUE TITLE
StatusMessage

### ISSUE THREAD

**Issue by jonsagara** [ITfoxtec/ITfoxtec.Identity.Saml2#138]
Hello,

Would you be willing to receive a pull request for retrieving the `StatusMessage` element from a response body?

It looks like it would happen in `Saml2Response.cs`, inside the `Read` method, just below the code to set the `Status` property.

Thank you,

Jon

**Comment by Revsgaard** [comment]
Yes absolutely. Please add both the read and write (GetXContent) operations.

**Comment by jonsagara** [comment]
I haven't forgotten about this. I'm trying to get my release out the door, and once that's done, I'll submit the pull request. 

Thank your for your excellent work!

**Comment by Revsgaard** [comment]
Closed, continued in the pull request.
