### ISSUE TITLE
Failure to Read/Unbind when receiving <saml2:Advice> element

### ISSUE THREAD

**Issue by piglione73** [ITfoxtec/ITfoxtec.Identity.Saml2#145]
Since the <saml2:Advice> element may contain assertions, in that case the Saml2AuthnResponse.GetAssertionElementReference fails with exception:
throw new Saml2RequestException("There is not exactly one Assertion element. Maybe the response is encrypted (set the Saml2Configuration.DecryptionCertificate).");

But that is not correct. The problem is probably the line just above the "throw" statement:
var assertionElements = XmlDocument.DocumentElement.SelectNodes($"//*[local-name()='{Schemas.Saml2Constants.Message.Assertion}']");

That statement uses the "//" XPath search operator, so it finds Assertions even inside the saml2:Advice element and that causes the method to fail.

**Comment by piglione73** [comment]
Please find an example attached.
[SAMLResponse with Advice element.txt](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/files/11846321/SAMLResponse.with.Advice.element.txt)

**Comment by Revsgaard** [comment]
This is currently not supported for security reasons. Feel free to make a pull request and I'll look into your code. But it has to be truly secure.
