### ISSUE TITLE
Tough time getting any of the code from the samples working

### ISSUE THREAD

**Issue by NickLWMP** [ITfoxtec/ITfoxtec.Identity.Saml2#147]
Ultimate goal is to configure an ASP.NET Core Web API.

I notice in the startup file there is a circular dependency. 

Startup.cs configures the `Saml2Configuration` and in the process calls the metadata controller
https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/blob/master/test/TestWebAppCoreAngularApi/Startup.cs#L47

`entityDescriptor.ReadIdPSsoDescriptorFromUrlAsync(httpClientFactory, new Uri(Configuration["Saml2:IdPMetadata"])).GetAwaiter().GetResult();`

The metadata controller constructor then has a DI dependency on the method that the above code is contained in
https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/blob/master/test/TestWebAppCoreAngularApi/Controllers/MetadataController.cs#L19

Using the code as is just makes the application hang until `ReadIdPSsoDescriptorFromUrlAsync` timesout.

I tried other samples, but get other errors such as certificate validation issue.

**Comment by derekmckinnon** [comment]
https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/blob/master/test/TestWebAppCoreAngularApi/Controllers/MetadataController.cs?rgh-link-date=2023-08-09T03%3A24%3A44Z#L19

^ this is the metadata endpoint for your Service Provider (SP).

The startup configuration is looking for the URI of the IdP's metadata URI - which should not be the same as the SP's!

**Comment by NickLWMP** [comment]
Ok, that makes a lot of sense! It works now. Thanks.
