### ISSUE TITLE
Compatibility with .NET Core 2.0

### ISSUE THREAD

**Issue by fedegiamporcaro** [ITfoxtec/ITfoxtec.Identity.Saml2#15]
Hi to all,

today i tried to add by NuGet the ITFoxtec.Identity.Saml2 and the ITFoxtec.Identity.Saml2.MvcCore (both on version 2.0.0) to my web app project (target framework .NET Core 2.0).
This operation failed and visual studio says this:

> Error NU1202. Package ITfoxtec.Identity.Saml2 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package ITfoxtec.Identity.Saml2 2.0.0 supports: net462 (.NETFramework,Version=v4.6.2)

But from the offical site (http://www.itfoxtec.com/IdentitySaml2) i read this: 

> Version: 2.0.0 - Supporting .NET 4.6.2 and Core 2.0.

I have wrong something or it's a bug?

Thanks,
dongigi92

**Comment by VictorioBerra** [comment]
I would like help with this too.

**Comment by mopinsk** [comment]
I have analyzed the code for compatibility with .NET Core and unfortunately **ITFoxtec.Identity.Saml2** relies on the full .NET Framework (>=4.5).
An example: the class "System.IdentityModel.Tokens.Saml2SecurityTokenHandler" is used in the project, but it isn't part of .NET Standard or .NET Core, it only is a part of the full .NET Framework. (Note that .NET Standard != .NET Framework).
So as long as there are references to classes that are only shipped with the full .NET Framework, there is no way to use it on .NET Core. (You can use it with ASP.NET Core running on the full .NET Framework though.)
I think @Revsgaard should update the documentation accordingly.

**Comment by Revsgaard** [comment]
I have specified in the documentation that Core 2.0 is full .NET Framework.

We are currently working on an update adding support for ASP.NET Core 2.1 without .NET Framework.

**Comment by rhysjtevans** [comment]
Any idea when the support for core 2.1+ is to be released?

**Comment by rhysjtevans** [comment]
Also where can we find examples running on aspnet core 2.2?

**Comment by Revsgaard** [comment]
.NET Core 2.1 is supported from https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/releases/tag/3.0.0
.NET Core 2.2 is supported from https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/releases/tag/3.0.1

.NET Core 2.2 IdP and RP exampels TestIdPCore and TestWebAppCore are found in https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/tree/master/test 

Both .NET Core  2.1 and 2.2 are supported without .NET Framework.
