### ISSUE TITLE
How to set Recipient in XML other than website used to POST SAML? How to set AuthnContextClassRef as unspecified?

### ISSUE THREAD

**Issue by PatryxCShark** [ITfoxtec/ITfoxtec.Identity.Saml2#151]
Hi,
I use your library in .NET 7.

I have few questions:
1. How to set recipient to X url and post to Y (different one) url?
When I set SingleSignOnDestination it is automatically post to the recipeint url.

2. How to set AuthnContextClassRef as unspecified (not PasswordProtectedTransport) to get:

```
<saml2:AuthnContext>
<saml2:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified</saml2:AuthnContextClassRef>
</saml2:AuthnContext>
```

**Comment by PatryxCShark** [comment]
Ad 1.  I found probably solution - set AuthnResponseSignType = Saml2AuthnResponseSignTypes.SignAssertion/

Please answer the 2 other questions.
Thank you in advance.

**Comment by Revsgaard** [comment]
1)
The IdP metadata support both Location and ResponseLocation, which can be read in the RP.
Sample ref: 
https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/blob/master/test/TestWebAppCore/Controllers/MetadataController.cs#L44

2)
In an IdP the AuthnContextClassRef URI can be set in the authnContext parameter in the CreateSecurityToken method.
Sample ref: 
https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/blob/master/test/TestIdPCore/Controllers/AuthController.cs#L174
