### ISSUE TITLE
Certificate rollover support

### ISSUE THREAD

**Issue by Zyano** [ITfoxtec/ITfoxtec.Identity.Saml2#153]
Currently the metadata support multiple signing and encryption certificates but the solution itself doesn't support multiple signing, encryption/decryption certificates.

This becomes a problem when multiple certificates are added to the metadata generation but not tested as part of the validation/decryption process. Do you have any thoughts on how this could/should be handled?

**Comment by Revsgaard** [comment]
I think it is a good idea and your code solution looks grate. I'll look into it.

**Comment by Revsgaard** [comment]
Implemented in commit  https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/commit/c1122eac6fcbe3decb980ba75ef3f7862d7a0c29. Thank you for the contribution.
