### ISSUE TITLE
[Feature Request] Target .Net 8 after GA

### ISSUE THREAD

**Issue by jeroenhabets** [ITfoxtec/ITfoxtec.Identity.Saml2#155]
We intend to start using your library for our solution's SAML 2.0 support so first of all many thanks for actively maintaining it!

One question: do you plan to publish a version to NuGet targeting .Net 8 after it GA's on November 14th 2023?

TIA!

**Comment by Revsgaard** [comment]
https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/commit/19142670bcf528cc1b65a24d4518ea470959979f

**Comment by jeroenhabets** [comment]
FYI: Still pending a (NuGet) release.

**Comment by Revsgaard** [comment]
Released in [4.10.5](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/releases/tag/4.10.5)
