### ISSUE TITLE
Possiblity to override Saml2IdentityConfiguration

### ISSUE THREAD

**Issue by dragoljub-exlrt** [ITfoxtec/ITfoxtec.Identity.Saml2#165]
Hello,

Is there any way to override Saml2Identity configuration? Specially to try to set the property _RequireExpirationTime_ to false, which is currently set to true by default?

I have a _SAMLResponse_ which does not have _NotOnOrAfter_ and _NotBefore_ attributes and I'm always getting the error:
`IDX10225: Lifetime validation failed. The token is missing an Expiration Time. Tokentype: 'Microsoft.IdentityModel.Tokens.Saml2.Saml2SecurityToken'.`

There must be something in configuration or option to overpass this, but without success. Tried to set _CertificateValidationMode_ to _None_, and to add new configuration 'Saml2Identity', but either I didn't register them properly, or it's not possible to override those.

Did you run into requests like this before, and is there anything I can change in configuration, to resolve this?

**Comment by Revsgaard** [comment]
I do not know if it is possible to omit `NotOnOrAfter` and `NotBefore` or not. They are not requeued according to the SAML 2.0 specification, but there is really not match security in a token without a valid time frame. 

Therefore, I’ll recommend you to require tokens with a valid time frame and close this issue.
