### ISSUE TITLE
Saml2SignedXml.CheckSignature()

### ISSUE THREAD

**Issue by Krisser50** [ITfoxtec/ITfoxtec.Identity.Saml2#17]
Hello

I have tried your nuget package of ITfoxtec.Identity.Saml2 and ITfoxtec.Identity.Saml2.Mvc and I found an issue.

Your CheckSignature function in ITfoxtec.Identity.Saml2.Cryptography.Saml2SignedXml always returns false.

If I use SignedXml directly it returns true.

I found that the 2 first lines in the function is causing the error:
```
SignedInfo.CanonicalizationMethod = XmlDsigExcC14NTransformUrl;
SignedInfo.SignatureMethod = Saml2Signer.SignatureAlgorithm;
```

The values before and after the equal-char is the same, so the lines doesn't change anything, but the "change" does something to the SignedXml-object that makes the function return false.

If I comment those two lines out, the function returns true.

I want to use your nuget instead of a local-copy.

I hope you can help to resolve this issue 👍 

Best regards

**Comment by bradgentry** [comment]
I've experienced the same result using both Okta and Ping identity providers.  Could it be because the setters for those 2 properties both set m_cachedXml to null (in SignedInfo.cs)?

**Comment by Revsgaard** [comment]
Hi,

Thanks for reporting the error. The problem i solved in this commit:
https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/commit/26f387fd25d5a42f47c8864b3082472efb0bf575

An updated NuGet version will be available shortly.

**Comment by Revsgaard** [comment]
Bug fix released https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/releases/tag/2.0.1
