### ISSUE TITLE
Saml2Configuration.AllowedAudienceUris is unnecessarily `protected`

### ISSUE THREAD

**Issue by Ghostbird** [ITfoxtec/ITfoxtec.Identity.Saml2#185]
`Saml2Configuration.AllowedAudienceUris` is seemingly unnecessarily `protected` which prevents initialising it. Might this be relaxed?

Init setters [are binding/reflection safe](https://stackoverflow.com/questions/65131217/are-c-sharp-9-init-properties-safe-to-use-for-configuration-binding-ioptions/65131543#65131543) and will allow us to create a correctly initialised `Saml2Configuration`. Instead of creating one, and then later adding the `AllowedAudienceUris`, which requires more code and splits the code across multiple statements which leaves the object accessible yet in an invalid state between those statements.

```csharp
 public IList<string> AllowedAudienceUris { get; init set; } = new List<string>();
```

EDIT: The same applies to `SignatureValidationCertificates`.

**Comment by Ghostbird** [comment]
Ah, I really didn't consider that this library cannot use `init` because it supports old framework versions that don't support that language construct.

Is it an option to make it public? That seems like it could lead to bugs.

**Comment by Revsgaard** [comment]
Thanks, it is fine to make it public.. I have changed to public in Saml2Configuration for SignatureValidationCertificates and AllowedAudienceUris.
