### ISSUE TITLE
Vulnerable to improper authentication attacks

### ISSUE THREAD

**Issue by StilgarISCA** [ITfoxtec/ITfoxtec.Identity.Saml2#19]
I'm no SAML expert, but I think that the use of [XmlDsigExcC14NTransformUrl](https://msdn.microsoft.com/en-us/library/system.security.cryptography.xml.signedxml.xmldsigexcc14ntransformurl(v=vs.110).aspx) when [computing the signature](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/blob/26f387fd25d5a42f47c8864b3082472efb0bf575/src/ITfoxtec.Identity.Saml2/Cryptography/Saml2SignedXml.cs#L28) and again when [checking the signature](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/blob/26f387fd25d5a42f47c8864b3082472efb0bf575/src/ITfoxtec.Identity.Saml2/Cryptography/Saml2SignedXml.cs#L39) makes your library vulnerable to [improper authentication as described by Duo Security](https://duo.com/blog/duo-finds-saml-vulnerabilities-affecting-multiple-implementations).

I _think_ you should be using [XmlDsigCanonicalizationWithCommentsUrl](https://msdn.microsoft.com/en-us/library/system.security.cryptography.xml.signedxml.xmldsigcanonicalizationwithcommentsurl(v=vs.110).aspx) instead.

**Comment by StilgarISCA** [comment]
Sounds like this has already been tested and passed. Sorry for not checking the closed issues first
https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/issues/18

**Comment by Revsgaard** [comment]
Quite alright and thanks for your comment.
