### ISSUE TITLE
Issue in package dependency System.IdentityModel.Tokens.Jwt version 7.0.3 

### ISSUE THREAD

**Issue by AMuirheadOTCX** [ITfoxtec/ITfoxtec.Identity.Saml2#190]
The version of the Jwt library which this library is dependant on has an DoS vulnerability, as outlined [here](https://github.com/dotnet/announcements/issues/290).

I have locally been able to update to the latest 7.5.0 without any issue, but only had dotnet8 installed so only tested that.

From a cursory look, it appears other versions are also impacted by a few medium vulnerabilities, that could be simply solved by a nuget update.

Thanks!

**Comment by Ghostbird** [comment]
See #188

**Comment by Revsgaard** [comment]
Pull request merged.
