### ISSUE TITLE
Sign AuthnRequest

### ISSUE THREAD

**Issue by Ghostbird** [ITfoxtec/ITfoxtec.Identity.Saml2#191]
This is kind of a follow-up to #23 but I didn't want to reanimate such an old and closed issue.

I needed a signed `AuthnRequest` too, and I found that:

- A post binding generates a signed request
- A redirect binding generates a non-signed request in a compressed query string parameter, and as a separate query string parameter, the signature of that compressed query string parameter is added.

I understand that this provides a more optimal communication method, But is there a particular reason why there's no option to sign the SAMLRequest XML document, instead of using a separate query string parameter? I'm trying to login somewhere, and from their documentation they expect the XML document to be signed.

**Comment by Ghostbird** [comment]
Ah, I managed to get it working using a `Saml2PostBinding` anyway.

**Comment by Revsgaard** [comment]
The SAML 2.0 standard defines that the XML document is signed within in a post binding and with a detached signature in redirect binding.
