### ISSUE TITLE
Getting Error while ReadSamlResponse

### ISSUE THREAD

**Issue by sirius93** [ITfoxtec/ITfoxtec.Identity.Saml2#197]
Readsamlresponse breaks with the following exception.

` Error occurred while authenticating - IDX13102: Exception thrown while reading 'Assertion' for Saml2SecurityToken. Inner exception: 'System.ArgumentException: IDX13515: SamlId value threw on XmlConvert.VerifyNCName. value: '1821e832d8254aca8c9b057f739208f6' ---> System.Xml.XmlException: Name cannot begin with the '1' character, hexadecimal value 0x31. at System.Xml.XmlConvert.VerifyNCName(String name, ExceptionType exceptionType) at Microsoft.IdentityModel.Tokens.Saml2.Saml2Id..ctor(String value) --- End of inner exception stack trace --- at Microsoft.IdentityModel.Tokens.Saml2.Saml2Id..ctor(String value) at Microsoft.IdentityModel.Tokens.Saml2.Saml2Serializer.ReadAssertion(XmlReader reader)'.`

I am not using any signing algorithm and it works for me with different saml Componentspace and IDP Saml-mock dev.

But using it with Itfoxtec is giving me this error.

**Comment by sirius93** [comment]
@Revsgaard 

Some help here 

This is my config looks like :

`{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
  "Saml2": {
    // "IdPMetadata": "http://localhost:5000/metadata",
    "Issuer": "saml-mock",
    "SingleSignOnDestination": "https://samlmock.dev/idp?aud=urn:saml-mock-demo&acs_url=http://localhost:5000/Auth/AssertionConsumerService",
    "SingleLogoutDestination": "https://samlmock.dev/idp_logout?callback_url=http://localhost:5000/Auth/Logout",
    // "SignatureAlgorithm": "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256",
    // "SigningCertificateFile": "itfoxtec.identity.saml2.testwebappcore_Certificate.pfx",
    // "SigningCertificatePassword": "!QAZ2wsx",
    //"SignatureValidationCertificateFile": "xxx.cer",
    "CertificateValidationMode": "None", // "ChainTrust"
    "RevocationMode": "NoCheck"
  }
}`

and the login code looks like this:

` [Route("Login")]
        public IActionResult Login(string returnUrl = null)
        {
            var binding = new Saml2RedirectBinding();
            binding.SetRelayStateQuery(new Dictionary<string, string> { { relayStateReturnUrl, returnUrl ?? Url.Content("~/") } });
            // binding.RelayState = $"RPID={Uri.EscapeDataString(serviceProviderRealm)}";

            // var config = new Saml2Configuration();

            config.Issuer = "https://samlmock.dev/";
            config.SingleSignOnDestination = new Uri("https://samlmock.dev/idp?aud=urn:saml-mock-demo&acs_url=http://localhost:5000/Auth/AssertionConsumerService");
            config.SingleLogoutDestination = new Uri("https://samlmock.dev/idp_logout?callback_url=http://localhost:5000/Logout");
            // config.SigningCertificate = CertificateUtil.Load(Startup.AppEnvironment.MapToPhysicalFilePath("itfoxtec.identity.saml2.testwebappcore_Certificate.pfx"), "!QAZ2wsx");
            // config.SignatureAlgorithm = Saml2SecurityAlgorithms.RsaSha256Signature;
            // config.SignatureValidationCertificate = CertificateUtil.Load(Startup.AppEnvironment.MapToPhysicalFilePath("itfoxtec.identity.saml2.testwebappcore_Certificate.cer"));
            var appliesToAddress = "https://samlmock.dev";

            return binding.Bind(new Saml2AuthnRequest(config)
            {
                //AssertionConsumerServiceIndex = 0,
                //AttributeConsumingServiceIndex = 0,
                //AssertionConsumerServiceUrl = new Uri("https://test.com"),

                //ForceAuthn = true,
                Subject = new Subject { NameID = new NameID { ID = "abcd" } },
                NameIdPolicy = new NameIdPolicy { AllowCreate = true, Format = "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent" },
                //Extensions = new AppExtensions(),
                //RequestedAuthnContext = new RequestedAuthnContext
                //{
                //    Comparison = AuthnContextComparisonTypes.Exact,
                //    AuthnContextClassRef = new string[] { AuthnContextClassTypes.PasswordProtectedTransport.OriginalString },
                //},
            }).ToActionResult();
        }`
        
        This code takes me to idp provider and on the assertion I am getting the error.
        
        `saml2AuthnResponse.InResponseTo = null
saml2AuthnResponse.InResponseToAsString ='saml2AuthnResponse.InResponseToAsString' threw an exception of type 'System.NullReferenceException'

`

**Comment by Ghostbird** [comment]
Your error seems correct. The `Id` value is `1821e832d8254aca8c9b057f739208f6` and according to the SAML standard:

> The xs:ID simple type is used to declare SAML identifiers for assertions, requests, and responses. Values
declared to be of type xs:ID in this specification MUST satisfy the following properties in addition to those
imposed by the definition of the xs:ID type itself

Note: _in addition to those imposed by the definition of xs:ID itself_

The [definition of xs:ID](https://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/datatypes.html#ID) states:

> The [·base type·](https://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/datatypes.html#dt-basetype) of ID is [NCName](https://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/datatypes.html#NCName).

> The [ID](https://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/datatypes.html#ID) datatype has the following [·constraining facets·](https://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/datatypes.html#dt-constraining-facet) with the values shown; these facets may be specified in the derivation of new types, if the value given is at least as restrictive as the one shown:

>[pattern](https://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/datatypes.html#rf-pattern) = \i\c* ∩ [\i-[:]][\c-[:]]*
>[whiteSpace](https://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/datatypes.html#rf-whiteSpace) = collapse

Then you need to reference [the regex definition](https://www.w3.org/TR/xmlschema-2/#dt-ccesN), which states:

> \i	the set of initial name characters, those [·match·](https://www.w3.org/TR/xmlschema-2/#dt-match)ed by [Letter](https://www.w3.org/TR/2000/WD-xml-2e-20000814#NT-Letter) | '_' | ':'

As you can see, by definition the `Assertion` tag's `ID` must start with a letter, an underscore character, or a colon.

I recently needed to look all  this up, as our SAML connection started rejecting messages from a government agency. They for some reason had changed their IDs to start with a number. Luckily it was on an acceptance environment, and after we notified them, they fixed it.

**Comment by Revsgaard** [comment]
The answer is correct. For the same reason I always begin the IDs with a underscore.
