### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by fabioscsharp** [ITfoxtec/ITfoxtec.Identity.Saml2#2]
Hi.

How can I run the sample projects, and what are the basic steps to use your library?

Thanks.

**Comment by Revsgaard** [comment]
Hi.

Please take a look on the ITfoxtec Identity Saml2 project site. I have added a describes for implementing a ASP.NET MVC Core Relying Party application.

ITfoxtec Identity Saml2 project site: http://itfoxtec.com/IdentitySaml2

Best regards
Anders Revsgaard
