### ISSUE TITLE
CertificateValidation and X509CertificateValidationMode / SignatureValidationCertificates

### ISSUE THREAD

**Issue by CaringDev** [ITfoxtec/ITfoxtec.Identity.Saml2#200]
Due to a recent change in our partners PKI signature certificates are not 'valid' (chain-verifiable) anymore and we get a `SecurityTokenValidationException` from `Saml2Binding.Unbind`.

I was under the impression, that either of the following would be enough to make validation pass:
1. adding certificates to `Saml2Configuration.SignatureValidationCertificates`
2. setting `Saml2Configuration.CertificateValidationMode` to `X509CertificateValidationMode.PeerOrChainTrust` and placing the used certificate in the trusted people store

Obviously _my assumption about 1. is wrong_, however I think that _2. not working is a bug_, as the [documentation](https://learn.microsoft.com/en-us/dotnet/api/system.servicemodel.security.x509certificatevalidationmode?view=net-8.0#fields) states, that the certificate should be valid if it satisfies _either_ of the conditions. Requiring peer _and_ chain validation [in Saml2CertificateValidator](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/blob/b2b1d5f891d84388c5baa036c48698afbb6a6fe4/src/ITfoxtec.Identity.Saml2/Util/Saml2CertificateValidator.cs#L34) seems too strict. See also [X509CertificateValidator.PeerOrChainTrust](https://github.com/microsoft/referencesource/blob/51cf7850defa8a17d815b4700b67116e3fa283c2/System.IdentityModel/System/IdentityModel/Selectors/X509CertificateValidator.cs#L257)

This won't fix my problem, as we can't modify the stores (in production)... so I'll implement a `CustomCertificateValidator` (s.a. [SO](https://stackoverflow.com/questions/77787321/a-certificate-chain-could-not-be-built-to-a-trusted-root-authority-after-upgr)). That is, unless there's a better idea? Maybe allow customizing the store (creation), [X509ChainPolicy](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509chainpolicy) or add something like `TrustedSignatureValidationCertificates`?

**Comment by Revsgaard** [comment]
Because you can't modify the cert store in production. I think the solution is to implement a X509CertificateValidator and set it on Saml2Configuration.CustomCertificateValidator.
