### ISSUE TITLE
Signature Invalid during Unbind

### ISSUE THREAD

**Issue by KrishLog** [ITfoxtec/ITfoxtec.Identity.Saml2#218]
I'm using Azure AD as SSO provider, below is the configuration - 

` samlConfig.Issuer = "https://sts.windows.net/{tenantid}/";
samlConfig.SingleSignOnDestination = "https://login.microsoftonline.com/{tenantid}/saml2";
 samlConfig.SignAuthnRequest = false;
..... `

I don't have a metadata url given to fetch the details using `entityDescriptor.ReadIdPSsoDescriptorFromUrlAsync` for getting `IdPSsoDescriptor.SigningCertificates` data.  And also there is no certificates available .

Because of it when reading the SAML response in AssertionConsumerService, it fails to unbind the response and errors out with `Invalid Signature` as there is no SigningCertificates provide while forming the samlconfig.

When i use the federation metadata url `https://sts.windows.net/{tenantid}/federationmetadata/saml20/federationmetadata.xml` it works fine as i get the SigningCertificates details. But i have a requirement to not use the federation metadata url.

Is there a way to handle this?

**Comment by Revsgaard** [comment]
You can configure it all by hand in code instead of using metadata.
