### ISSUE TITLE
Support for multi tenant scenario?

### ISSUE THREAD

**Issue by keshavkaul** [ITfoxtec/ITfoxtec.Identity.Saml2#220]
Curious to understand how multi tenancy is supported or not. If not, then can we customize the behaviour?

**Comment by Revsgaard** [comment]
[FoxIDs.com](https://www.foxids.com) support multi tenancy and is implemented on top of ITfoxtec Identity SAML2. 

You can add the support to ITfoxtec Identity SAML2 with code, please see:
- https://stackoverflow.com/questions/59761654/can-itfoxtec-saml2-supprot-multiple-idps
- https://stackoverflow.com/questions/77993773/using-multiple-id-providers-with-itfoxtec-identity-saml-2-library
-
