### ISSUE TITLE
Usage regression with ADFS

### ISSUE THREAD

**Issue by glatzert** [ITfoxtec/ITfoxtec.Identity.Saml2#225]
Hi there,

thanks for your great work with this library, that allows us (the university of Mainz) to bring Passkey-Authentication to ADFS, by making a Passkey Auth Server, that acts as a IdP (https://github.com/jguzdv/Passkey-Authentication)

Unfortunately 4.13 has a regression, that let's ADFS fail:
https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/blob/feae3f47028ae70722cf5f70f71742d2ce23fdfd/src/ITfoxtec.Identity.Saml2/Cryptography/Saml2SignedXml.cs#L39

The stubborn thing (= ADFS), does not like the addition of the KeyName.
Do you think, we can do anything to make it configurable?
We'll happily provide developer time to solve it, if that's okay with you.

**Comment by Revsgaard** [comment]
Okay I did not know AD FS did not like that. Maybe `KeyName` should only be included if configured?

You are very welcome to create a pull request where `KeyName` is made configurable.

**Comment by glatzert** [comment]
> Okay I did not know AD FS did not like that.
We neither .. ADFS is breaking apart, since it's getting old now. No ECDSA, only CBC among others ...

Can you elaborate the reasoning behind adding the KeyName? I think the de facto reference SAML2 implementation (Shib IdP) does not include it.

**Comment by Revsgaard** [comment]
The KeyInfoName is configurable in version [4.13.2](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/releases/tag/4.13.2).
