### ISSUE TITLE
SAML Response not encrypted

### ISSUE THREAD

**Issue by franmib** [ITfoxtec/ITfoxtec.Identity.Saml2#226]
Hi!
thanks for your great work with this library, it let me develop at .NET on a PHP world at my university.

When you login on SAML the AssertionConsumerService return a SAML response message desencrypted and you can see  any  <saml:Attribute> with a SAML tracer plugin on your navigator.
I haven`t find the option to do this.
Any insights or suggestions on how to resolve this issue would be greatly appreciated. Thank you!
Thanks with you and community support.

**Comment by Revsgaard** [comment]
You need to add an [EncryptionCertificate in settings](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/blob/main/src/ITfoxtec.Identity.Saml2/Configuration/Saml2Configuration.cs#L46). If set the authn responses created by the library is encrypt.

**Comment by franmib** [comment]
Thank you so much, with this setting and putting the correct certificate at xml metadata from IDP its works.
