### ISSUE TITLE
Send Signed AuthnRequest

### ISSUE THREAD

**Issue by teruobr** [ITfoxtec/ITfoxtec.Identity.Saml2#23]
Hi, I'm trying to connect to a client IdP and I need to send a signed AuthnRequest (with ds:Signature elements) with the cert value so I can successfully log in the IdP with my Sp.

I am using a Service Fabric Application (hosted in Azure) with .net Core.

I couldn't find anything on how to create this elements with this solution.

Thanks in advance.

**Comment by Revsgaard** [comment]
Hi,

You can use either Saml2PostBinding or Saml2RedirectBinding and set the saml2Configuration.SignAuthnRequest to true.

Regards
Anders
