### ISSUE TITLE
Can't see my certificate

### ISSUE THREAD

**Issue by CiberOskar** [ITfoxtec/ITfoxtec.Identity.Saml2#24]
I'm setting up a service provider I and are using this SAML library. My request looks like this

> <saml2p:AuthnRequest
    Destination="https://qa.connector.eidas.swedenconnect.se/idp/profile/SAML2/POST/SSO"
    ForceAuthn="true" ID="_64ef67e7-1cd8-4f68-9bf7-a2d5d8fd8856" IsPassive="false"
    IssueInstant="2018-07-05T11:54:39.3284774+02:00" Version="2.0"
    xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"
    xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol">
    <saml2:Issuer>https://eunode.eidastest.se/con-sp/metadata</saml2:Issuer>
</saml2p:AuthnRequest>

but it should look like this

> €‹<saml2p:AuthnRequest
    Destination="https://qa.connector.eidas.swedenconnect.se/idp/profile/SAML2/POST/SSO"
    ForceAuthn="true" ID="_ed56499e69da8bdd1d479ef96807e57c" IsPassive="false"
    IssueInstant="2018-07-05T09:53:37.226Z"
    ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Version="2.0"
    xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol">
    <saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity"
        xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">https://eunode.eidastest.se/con-sp/metadata</saml2:Issuer>
    <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:SignedInfo>
            <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
            <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
            <ds:Reference URI="#_ed56499e69da8bdd1d479ef96807e57c">
                <ds:Transforms>
                    <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                    <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
                </ds:Transforms>
                <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
                <ds:DigestValue>VXceOb2vz5OAJPWUH+0G58x1VsEJ6lQl6ErnFf+22AQ=</ds:DigestValue>
            </ds:Reference>
        </ds:SignedInfo>
        <ds:SignatureValue>
            Mo0+sHd/1SUfQs17lBcfYKSNgmbAjptiNc1l9ZLCeF0nCrYBRw7t2fngLR8t9NAXNwdezTnkXV/N
            FOSBPZiWy8BwzUD7+yW+hTfnU+1DRCfpeJgub7TgJd0BG1AvR3QCcFfOtOtExnZqoYo1f5lFlbqO
            I0r6MCuoBMRGSy7kusjBpxYvsNBYUopTv2DEvC2jtQFu4CDj8RkQGXzCXx2nyf6rluOkOwxnNqi2
            bMjJqxgWP4s19wIKgq7+vesvS2nLUwoPeGYw0G5y4DP010SYvNTRFWgGMRZfWxKr1Je/WsQI6d6V
            8g6Y8v92sR/zRJimhi6CA7EJROubbubB3fa1LQ==
        </ds:SignatureValue>
        <ds:KeyInfo>
            <ds:X509Data>
                <ds:X509Certificate>MIIDIzCCAgsCBgFgtkRcgjANBgkqhkiG9w0BAQ0FADBVMR0wGwYDVQQDExRTRSBDb25uZWN0b3IgRGVtbyBTUDEnMCUGA1UEChMeU3dlZGlzaCBFLUlkZW50aWZpY2F0aW9uIEJvYXJkMQswCQYDVQQGEwJTRTAeFw0xODAxMDIwNzQ3MDFaFw0yMzAxMDIwOTQ3MDFaMFUxHTAbBgNVBAMTFFNFIENvbm5lY3RvciBEZW1vIFNQMScwJQYDVQQKEx5Td2VkaXNoIEUtSWRlbnRpZmljYXRpb24gQm9hcmQxCzAJBgNVBAYTAlNFMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnT0borSI1StrlVaeDjJJdp4gSxiVud1J1n7+mX6W5C5/nKLLUY4kNHu7lpMCAV9bi0/er++3bwtpPcyKhSvjA3szTo8QMpBknL0Au2FgYL+Eqk/S+R2r9KBtVUoq/j/jAvZM9vkRNclM3rLovbm2FLS8Z+CJ56wDa6q1f99VzdmsPydvLeaRuxIEmjRzcq/zI1uiP7aVtAGXo5kbI+IpRHziV5kQ6R7e5v26nwOUeKidUQZGxElPmez/xRkpX0aqt/XEV6SG+dehsvPHVTzpp0Yj9rIuokFKUh7vq87roUJHircl7KHVaupyyWkhiwCbMncJszG6YwoW6Ecm2XDEOQIDAQABMA0GCSqGSIb3DQEBDQUAA4IBAQCKFZffnIDECp3/A40UURFwaBXo3rIlcRrO9DUVALsG7fg3079FH5TmC+xPKf2tMgIZjAglWeVa7XFf0Lm1Qpk0eNhraAXBmDYXiyHCk1ndTHZhHwPX0rKk74dUXvp8FauNnL5yZK9dD6GlsTSRdR5L6HMjtD1leYr3siAmxya3f6Mc5i28LmttZj9ZAipskDsipIQmlVY/tNxQV5bO7vcByBA6b/sL+Wh9oApsYc+0El/6uDhVuIho1aWVRB7ZDuOS+NJ3TTFgx6B3oeGXygi/UqcSC/nkKH6yzSo3O9jNERnVaQcl9RHJba7QRimfvvRFwHs++DeI//ya4wMTOnAA</ds:X509Certificate>
            </ds:X509Data>
        </ds:KeyInfo>
    </ds:Signature><saml2p:NameIDPolicy AllowCreate="true"/>
    <saml2p:RequestedAuthnContext Comparison="exact">
        <saml2:AuthnContextClassRef xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">http://id.elegnamnden.se/loa/1.0/eidas-sub</saml2:AuthnContextClassRef>
    </saml2p:RequestedAuthnContext>
</saml2p:AuthnRequest>
 
I have set up a RegisterIdentity method but can't see my certificate 

`public ActionResult Login(string returnUrl = null)
		{
			var binding = new Saml2RedirectBinding();
			//var binding = new Saml2PostBinding();
			binding.SetRelayStateQuery(new Dictionary<string, string> { { relayStateReturnUrl, returnUrl ?? Url.Content("~/") } });

			var saml2Configuration = RegisterIdentity();

			XmlDocument xD = new XmlDocument();

			var saml2AuthnRequest = new Saml2AuthnRequest(saml2Configuration);

			var hej = new Saml2AuthnRequest(saml2Configuration);
			
			var test = binding.Bind(new Saml2AuthnRequest(saml2Configuration)
			{
				Destination = new Uri(ConfigurationManager.AppSettings["Saml2:Destination"]),
				ForceAuthn = true,
				//Set automatic
				IsPassive = false,
				IssueInstant = DateTime.Now,
				//Protocolbinding
				Version = "2.0",
				//Issuer = new Uri("https://eunode.eidastest.se/con-sp/metadata"),
				
			}).ToActionResult();
			//return ITfoxtec.Identity.Saml2.Mvc.Saml2BindingExtensions.ToActionResult(returnUrl2);
			return test;
			
		}

		public Saml2Configuration RegisterIdentity()
		{
			//var x509cert = new X509Certificate2(ConfigurationManager.AppSettings["x509:CertificatePathAndName"]);
			var saml2Configuration = new Saml2Configuration();
			var path = ConfigurationManager.AppSettings["x509:CertificatePathAndName"];
			saml2Configuration.SigningCertificate = CertificateUtil.Load(ConfigurationManager.AppSettings["x509:CertificatePathAndName"], "test");
			saml2Configuration.SignatureAlgorithm = ConfigurationManager.AppSettings["Saml2:SignatureAlgorithm"];
			saml2Configuration.Issuer = new Uri(ConfigurationManager.AppSettings["Saml2:Issuer"]);

			return saml2Configuration;
		}`

When I'm debugging the code, the signing certificate and signature algorithm are set

**Comment by Revsgaard** [comment]
Hi,

You need to user a Saml2PostBinding and set
the saml2Configuration.SignAuthnRequest to true.



Venlig hilsen / Best regards
Anders Revsgaard
Mobil: 50595808
www.ITfoxtec.com <http://itfoxtec.com/>

Reklame:
*Sortingtime*
https://sortingtime.com tracks time, and send PDF invoices and reports.

2018-07-05 12:09 GMT+02:00 BouvetOskar <notifications@github.com>:
