### ISSUE TITLE
SecurityTokenValidFrom gives an exception

### ISSUE THREAD

**Issue by Krisser50** [ITfoxtec/ITfoxtec.Identity.Saml2#26]
Hello

I am having an error, and I think I have located the bug..

When I call: saml2AuthnResponse.CreateSession(HttpContext, claimsTransform: ClaimsTransform.Transform)
I get the error: ArgumentOutOfRangeException: The UTC time represented when the offset is applied must be between year 0 and 10,000

Which is coming from "saml2AuthnResponse.SecurityTokenValidFrom" in the CreateSession-function.

I can see that the type of saml2AuthnResponse.SecurityTokenValidFrom has been changed from DateTime to DateTimeOffset, and the service I call is not defining a "ValidFrom", and therefore the value is never set.

DateTimeOffset does not work with DateTime.MinValue

My work-around is this: (ITfoxtec.Identity.Saml2.Saml2AuthnResponse)
        public DateTimeOffset SecurityTokenValidFrom { get { return Saml2SecurityToken.ValidFrom > DateTime.MinValue ? Saml2SecurityToken.ValidFrom : DateTime.UtcNow; } }

Then the system works, even if the assertion does not come with a ValidFrom-value

Best regards, and thanks for a great framework :)

Christian

**Comment by Revsgaard** [comment]
Hi Christian

Thank you :) 

I have added your code change https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/commit/04f1f519bff3437985771da8b6eebe3fa0a07166

The change is part of the next version 3.0.1.

Best regards, and thanks again :)
Anders

**Comment by Revsgaard** [comment]
Hi Christian

I have updated the code to both handle min and max related out of range protection https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/commit/4319a206d308d368772755442fcefdfa71da14b3

Please let me know if this new change also solves your problem.

Best regards, 
Anders

**Comment by Krisser50** [comment]
Hi Anders

Thanks for the update, and sorry for my late one. I haven't worked with the specific project this past week.

But I have tested the code now, and it seems to work just fine now :)

Thanks a lot

Best regards

Christian

**Comment by Revsgaard** [comment]
Hi Christian

Thank you for testing the code :)

This issue is solved in release https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/releases/tag/3.0.1

Best regards,
Anders
