### ISSUE TITLE
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The system cannot find the file specified

### ISSUE THREAD

**Issue by phi1ipp** [ITfoxtec/ITfoxtec.Identity.Saml2#28]
While running on w2012 under IIS, got the exception trying to load certificate from the file. I use in-process hosting with ApplicationPoolIdentity
```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The system cannot find the file specified
   at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(Byte[] rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags)
   at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at ITfoxtec.Identity.Saml2.Util.CertificateUtil.Load(String path, String password)
```
here is my code fragment
```c#
public void ConfigureServices(IServiceCollection services)
{
    CultureInfo.CurrentCulture = new CultureInfo(Configuration.GetValue<string>("DefaultCulture"));

    services.Configure<Saml2Configuration>(Configuration.GetSection("Saml2"));
    services.Configure<Saml2Configuration>(saml2Configuration =>
    {
        saml2Configuration.SignAuthnRequest = true;
        saml2Configuration.SigningCertificate = CertificateUtil.Load(
            Configuration["Saml2:SigningCertificateFile"], Configuration["Saml2:SigningCertificatePassword"]);
```
The file is in place, I tried both absolute and relative paths. It works if I use `dotnet run` under MacOS.

Stumbled across the following discussion https://github.com/dotnet/corefx/issues/14745 and this one https://github.com/dotnet/corefx/issues/23780 I hope it might be helpful to troubleshoot/fix

**Comment by phi1ipp** [comment]
Based on one of those corefx bugs I tried to patch your library to use a combination of MachineKey | EphemeralKey flags when loading pfx, which worked for me. But I guess it's better for you to evaluate if it's something you would want to do.

**Comment by Revsgaard** [comment]
I would like to look into this, maybe the best solution is to add a CertificateUtil.Load method that include the X509KeyStorageFlags parameter.

@phi1ipp, to be sure, did this code work on Windows 2012 under IIS?
new X509Certificate2(path, password, X509KeyStorageFlags.MachineKeySet | X509KeyStorageFlags.EphemeralKeySet)

**Comment by phi1ipp** [comment]
@Revsgaard, I was able to start the app normally at least. I need to run some tests with the customer to confirm that all is fine, as the certificate is used during SLO.

I had to give up 4.6 support target, as those keys (enum) are only supported starting from 4.7.

Thank you for the prompt reply, I'll keep you updated.

**Comment by phi1ipp** [comment]
@Revsgaard, I can confirm that this set of flags works for my customer in Win2008

**Comment by Revsgaard** [comment]
@phi1ipp, thanks for replying back on your test.

The CertificateUtil is extended with two methods supporting X509KeyStorageFlags. The update is included in the next version 4.0.0.

The flags can be set as follows:

```
public void ConfigureServices(IServiceCollection services)
{
    CultureInfo.CurrentCulture = new CultureInfo(Configuration.GetValue<string>("DefaultCulture"));

    services.Configure<Saml2Configuration>(Configuration.GetSection("Saml2"));
    services.Configure<Saml2Configuration>(saml2Configuration =>
    {
        saml2Configuration.SignAuthnRequest = true;
        saml2Configuration.SigningCertificate = CertificateUtil.Load(
            Configuration["Saml2:SigningCertificateFile"], Configuration["Saml2:SigningCertificatePassword"], X509KeyStorageFlags.MachineKeySet | X509KeyStorageFlags.EphemeralKeySet);
```

**Comment by phi1ipp** [comment]
Cool, thank you for the prompt fix!

**Comment by Revsgaard** [comment]
[version 4.0.0](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/releases/tag/4.0.0) is released solving the issue.
