### ISSUE TITLE
Saml2RedirectBinding.RedirectLocation parameters end up not being encoded by Uri.EscapeDataString

### ISSUE THREAD

**Issue by raphael-cavallero** [ITfoxtec/ITfoxtec.Identity.Saml2#3]
Hello,

I'm trying to send a AuthnRequest to an Idp with a redirect binding (not using .NET MVC here) and the HTTP request parameters look like they're not being encoded by Uri.EscapeDataString. e.g. I get some "/" instead of "%2F" inside my SAMLRequest and signature.

I ended up looking at line 39 of ITfoxtec.Identity.Saml2.Saml2RedirectBinding where requestQueryString still contains the correctly encoded strings.
After the call to new Uri(...), escaped characters are reverted back to their original state ("%2F" -> "/")  in RedirectLocation.

Can you do anything to fix this ? Everything else seems ok but we might have to (reluctantly) switch to a closed source library if i can't convince my boss quickly enough that your library is what we need :(

Regards

**Comment by Revsgaard** [comment]
Hi,

The RedirectLocation is used in the Saml2BindingExtensions class when the ToActionResult method is called. The call result in a redirect to binding.RedirectLocation.OriginalString. Therefore the url is not escaped in RedirectLocation.

Regards
Anders

**Comment by raphael-cavallero** [comment]
Allright, sorry.
I hope you can work out a separate documentation for non-MVC ASP cause i thought i was supposed to use this URI (RedirectLocation) as is in Response.Redirect() and our IdP wanted encoded parameters, thus could not read our requests.
Thanks anyway
Regards
