### ISSUE TITLE
Certificate Store Find issue

### ISSUE THREAD

**Issue by renier-venter** [ITfoxtec/ITfoxtec.Identity.Saml2#30]
When a thumbnail find is done on certificate store it errors out with "Invalid find value" error, 
certificate.GetCertHash() needs to be replaced with certificate.GetCertHashString()

File : Saml2CertificateValidator.cs
Method: ValidatePeerTrust

**Comment by Revsgaard** [comment]
You are right, thank you for the error correction.
The code is changed to use certificate.GetCertHashString() https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/commit/be84452bd076168d418c2a8b3803cd765446e762.

The correction will be included in the next version (Version 4.0.0).

**Comment by Revsgaard** [comment]
[version 4.0.0](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/releases/tag/4.0.0) is released solving the issue.
