### ISSUE TITLE
IdP metadata doesn't support optional "use" attribute on KeyDescriptor

### ISSUE THREAD

**Issue by peteat** [ITfoxtec/ITfoxtec.Identity.Saml2#31]
When reading in the IdP metadata (`IdPSsoDescriptor`), the signing/encryption certificates are missed if the `use` attribute is missing from the `KeyDescriptor` element. 

As per https://docs.oasis-open.org/security/saml/v2.0/saml-schema-metadata-2.0.xsd (and https://wiki.shibboleth.net/confluence/display/CONCEPT/SAMLKeysAndCertificates) the `KeyDescriptor/@use` XML attribute is an optional attribute. 

Could I suggest, as per the shibboleth wiki, that a KeyDescriptor with no `use` attribute should be considered as containing keys for both signing and encryption? 
i.e. update the `Read()` method of `ITfoxtec.Identity.Saml2.Schemas.Metadata.IdPSsoDescriptor` to read and add certificates with no `use` attribute into both the `SigningCertificates` and `EncryptionCertificates` properties. 

Thanks!

**Comment by peteat** [comment]
I've created a PR with a suggested fix. I'll leave it to you to decide if you want to incorporate it or not :)

**Comment by Revsgaard** [comment]
Thank you @peteat for your contribution. I have changed your pull request slightly and the change will be part of the next version. Then a KeyDescriptor with no use attribute is considered as containing keys for both signing and encryption.

**Comment by peteat** [comment]
Ah, yes, that's a better way of doing it. Glad I could help :)

**Comment by Revsgaard** [comment]
[version 4.0.0](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/releases/tag/4.0.0) is released solving the issue.
