### ISSUE TITLE
how to set SignatureAlgorithm before ReadSamlResponse?

### ISSUE THREAD

**Issue by Simplebear** [ITfoxtec/ITfoxtec.Identity.Saml2#35]
when my acs get the SMAL Response, I must get the IDP SignatureAlgorithm  by issuer,but i only get the issuer after ReadSamlResponse,so,I can`t set the SignatureAlgorithm .so, what should  I do?

**Comment by Revsgaard** [comment]
I'll recommend you to set set the SignatureAlgorithm in configuration and not let the IdP or er potentially hacker set the SignatureAlgorithm. This weakness can of cores be eliminated by having a list of accepted signature algorithms.
If you still want the ReadSamlResponse to read the SignatureAlgorithm you are wellcomm to do a pool request and I'll add the functionality.
