### ISSUE TITLE
The NameClaimType of IdentityConfiguration/TokenValidationParameters is not configurable

### ISSUE THREAD

**Issue by legoadk** [ITfoxtec/ITfoxtec.Identity.Saml2#36]
Some background: Our SAML service provides us 
 a user name along with other attributes of the user when authentication is successful. When we assign claims (in your example code, this is done in the ClaimsTransform class) and create a claim of `ClaimType.Name` with the user's real name, we expected to see this reflected in views when we use `User.Identity.Name`.

Instead, it looks as though this package hard-codes the Identity `NameClaimType` to `ClaimType.NameIdentifier`, which is typically a GUID or other unique identifier. As a result, that ID is provided when using `User.Identity.Name`, instead of the default behaviour of using the value of a claim of type `ClaimType.Name`.

This hard-coding happens here:
https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/blob/8b084740abae08779368463fc71cd0208d43878e/src/ITfoxtec.Identity.Saml2/Configuration/Saml2IdentityConfiguration.cs#L49

Would there be any side effects to allowing this to be configurable? I don't see any other reference to `Identity.Name` within this package that rely on it returning `NameIdentifier` (as opposed to `Name`).

**Comment by Revsgaard** [comment]
The ClaimsIdentity NameClaimType and RoleClaimType can be changed in the ClaimsTransform class, see the ASP.NET Core sample: 

https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/blob/master/test/TestWebAppCore/Identity/ClaimsTransform.cs#L31

If you want to use the Name claim as the NameClaimType the line is changed to:
 
return new ClaimsPrincipal(new ClaimsIdentity(claims, incomingPrincipal.Identity.AuthenticationType, ClaimTypes.Name, ClaimTypes.Role)

**Comment by legoadk** [comment]
I totally missed this, thank you. That should do the trick.
