### ISSUE TITLE
[Question] can the sample project run on Ubuntu 18.04 (Linux)?

### ISSUE THREAD

**Issue by nghiepvo** [ITfoxtec/ITfoxtec.Identity.Saml2#37]
hello!

I can't run test project on Ubuntu 18.04, could you help me about that?

**Comment by Revsgaard** [comment]
It should be possible to run the ASP.NET Core samples [TestIdPCore](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/tree/master/test/TestIdPCore) and
[TestWebAppCore](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/tree/master/test/TestWebAppCore). 
But I have not tested on Linux or Ubuntu.

**Comment by Revsgaard** [comment]
Have you succeed to run the ASP.NET Core samples TestIdPCore and
TestWebAppCore?
