### ISSUE TITLE
rsa-sha1 is not support. Error when I Try to add saml2Configuration.SignatureAlgorithm = Saml2SecurityAlgorithms.RsaSha1Signature;

### ISSUE THREAD

**Issue by maznag** [ITfoxtec/ITfoxtec.Identity.Saml2#39]
I want to add RSA-SHA1 certificate to sign AutnNRequest but I got this error when I try to login:
<code>
{
  "errors": [
    {
      "message": "Object reference not set to an instance of an object.",
      "type": "System.NullReferenceException",
      "raw": "System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at ITfoxtec.Identity.Saml2.Cryptography.Saml2Signer.GetSignatureDescription()\r\n   at ITfoxtec.Identity.Saml2.Cryptography.Saml2Signer.CreateFormatter()\r\n   at ITfoxtec.Identity.Saml2.Cryptography.Saml2SignedText.SignData(Byte[] input)\r\n   at ITfoxtec.Identity.Saml2.Saml2RedirectBinding.SigneQueryString(String queryString, X509Certificate2 signingCertificate)\r\n  
 at ITfoxtec.Identity.Saml2.Saml2RedirectBinding.BindInternal(Saml2Request saml2RequestResponse, String messageName)\r\n   at ITfoxtec.Identity.Saml2.Saml2Binding`1.Bind(Saml2Request saml2Request)\r\n   at AFD.BackOffice.Controllers.Saml2AuthController.Login(String returnUrl) in C:\\Dev\\socle-angular\\afd-socle-angular-back\\AfdBackOffice\\Controllers\\Saml2AuthtController.cs:line 49\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\r\n   at 
Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at 
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\r\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\r\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Hellang.Middleware.ProblemDetails.ProblemDetailsMiddleware.Invoke(HttpContext context)",
</code>

**Comment by Revsgaard** [comment]
Thank you the contribution. But I'll recommend you NOT to use SHA1 because it is implemented.
