### ISSUE TITLE
Unable to set custom certificate validator in Saml2Configuration on .net full

### ISSUE THREAD

**Issue by zabulus** [ITfoxtec/ITfoxtec.Identity.Saml2#47]
Hi.

I'm trying to specify custom validator on .net 4.8 by following code:
```
Saml2Configuration.CertificateValidationMode = X509CertificateValidationMode.Custom;
Saml2Configuration.CustomCertificateValidator = new MetadataCertificateValidator(entityDescriptor.IdPSsoDescriptor.SigningCertificates);
```
Configuration created successfully, but error occurs when trying to initiate request.
The library throws from the following code:
https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/blob/master/src/ITfoxtec.Identity.Saml2/Configuration/Saml2IdentityConfiguration.cs#L41
Exception Error Message:
`ID4280: The X509CertificateValidationMode is set to Custom but the CertificateValidator property has not been set. You must set the CertificateValidator property to use a custom validator.`
Call Stack of Exception:
```
 	System.IdentityModel.dll!System.IdentityModel.Configuration.IdentityConfiguration.Initialize() Line 338	C#
 	ITfoxtec.Identity.Saml2.dll!ITfoxtec.Identity.Saml2.Configuration.Saml2IdentityConfiguration.GetIdentityConfiguration(ITfoxtec.Identity.Saml2.Saml2Configuration config) Line 30	C#
 	ITfoxtec.Identity.Saml2.dll!ITfoxtec.Identity.Saml2.Saml2Request.Saml2Request(ITfoxtec.Identity.Saml2.Saml2Configuration config) Line 67	C#
 	ITfoxtec.Identity.Saml2.dll!ITfoxtec.Identity.Saml2.Saml2AuthnRequest.Saml2AuthnRequest(ITfoxtec.Identity.Saml2.Saml2Configuration config) Line 34	C#
```

I think the issue is about order of execution. In Saml2IdentityConfiguration.cs `Saml2IdentityConfiguration.SetCustomCertificateValidator(configuration, config);` should be called before `configuration.Initialize();`

**Comment by Revsgaard** [comment]
Thank you.

I think you are correct. Do you think this commit https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/commit/e53220940b34a4fd0f3deb783bd61372d370b64f solves the problem?

**Comment by zabulus** [comment]
Yes, looks good. When can you publish this fix to nuget?

**Comment by Revsgaard** [comment]
I have released a beta version including the change https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/releases/tag/4.0.6-beta1. Please test and let me know if it works.

**Comment by zabulus** [comment]
I've just checked the version - works fine. Thanks

**Comment by Revsgaard** [comment]
Perfect :)
