### ISSUE TITLE
Support for Artifact Bindings

### ISSUE THREAD

**Issue by lemoinem** [ITfoxtec/ITfoxtec.Identity.Saml2#53]
The library seems great, but we would need support for Artifact Bindings in addition to Redirect.
We would be open to provide a PR for it, be I would like a few more details before starting working on it.

We only need the "Resolve an Artifact" part of the binding (i.e., we receive a SAML Artifact and need to contact the other side in order to get its content).

Is it something you would be open to add to the library?
What scope would be acceptable for you? Is resolving only OK or would you insist on supporting creation as well?

Resolving an artifact should be easy enough to do. It's just a POST binding with an additional step.
Once coded, integrating it to the various IdP/SP handlers shouldn't be too hard either.

Creating an artifact might be more complex and would require some form of transient storage/repository.
I was thinking a simple Repository interface (`Store(Key,Artifact)`/`FetchAndRemove(Key)`) along with a simple In-Memory storage would cover the most simple cases easily (single webserver). Allowing the user to specify their own implementation of the Repository would make it easy to adapt to any complex setup (load-balancing, farm, cloud, etc.) without assuming the user's infra.

As mentioned, if the feature is interesting to you and we can agree on a scope and direction we are open to working toward a PR.

**Comment by Revsgaard** [comment]
Hi Mathieu 

I think it would be great if you contribute with support for Artifact Bindings.

Naturally it would be best if support for both resolving and creation was added. But it is also very okay only to add support for resolving. Who knows, maybe you find it relatively easy to add creation after adding resolving support :)

In advance thank you.

**Comment by Revsgaard** [comment]
This thread has been inactive for awhile, therefore I'll will close it.
