### ISSUE TITLE
Amazing job, looking for contributing.

### ISSUE THREAD

**Issue by flarocca** [ITfoxtec/ITfoxtec.Identity.Saml2#54]
Hi guys, 

I came accross this amazing library last week since I had to support a legacy integration using SAML for PingFederated for one of our customers.

So on the one hand, I want to congratulate you guys because of the excellent job you've done. On the other, I would like to contribute somehow.
I am a software engineer, sometimes architect, sometimes tech lead, sometimes developer, and sometimes just a simple learner.
So I can even contribute translating the site to Spanish, as I am argentinian and a native spanish speaker.

**Comment by Revsgaard** [comment]
Hi Facundo

Thank you very much for your kind comment and thank you for offering to contribute.

I'm mostly working with security and I have created some security components other then this one for SAML 2.0. [ITfoxtec.Identity](https://github.com/ITfoxtec/ITfoxtec.Identity) supporting OAuth 2.0 and OIDC, [OIDC support in Blazor WebAssembly](https://github.com/ITfoxtec/ITfoxtec.Identity.BlazorWebAssembly.OpenidConnect) implemented in C#. 
And most importantly I'm currently working on [FoxIDs](https://github.com/ITfoxtec/FoxIDs) which is a open source cloud security system supporting SAML 2.0, OAuth 2.0 and OIDC. FoxIDs relay on the other open source components to support the standards.

Would you also if possible be interested in contributing to [FoxIDs](https://github.com/ITfoxtec/FoxIDs) or is you mostly for the SAML 2.0 component?

Regards,
Anders

**Comment by Revsgaard** [comment]
This thread has been inactive for awhile, therefore I'll will close it.
