### ISSUE TITLE
Error on SAML response. System.ArgumentNullException: Value cannot be null. Parameter name: certificate

### ISSUE THREAD

**Issue by zabulus** [ITfoxtec/ITfoxtec.Identity.Saml2#55]
Stacktrace is the following:
```
Parameter name: certificate
System.ArgumentNullException: Value cannot be null.
Parameter name: certificate
   at System.Security.Cryptography.X509Certificates.RSACertificateExtensions.GetRSAPublicKey(X509Certificate2 certificate)
   at ITfoxtec.Identity.Saml2.Saml2AuthnResponse..ctor(Saml2Configuration config)
```
Looks like a bug in following code:
https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/blob/46084fdd553ec31ba363b110050ca268738a6486/src/ITfoxtec.Identity.Saml2/Request/Saml2AuthnResponse.cs#L76
This should be ```config.EncryptionCertificate.GetRSAPublicKey()```.
Correct me if I'm wrong.

Issue was found during integration with ADFS SSO.

**Comment by Revsgaard** [comment]
Thank you for reporting the issue, the problem is solved in https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/releases/tag/4.0.8
