### ISSUE TITLE
Idp on .net classic

### ISSUE THREAD

**Issue by maxsmaleha** [ITfoxtec/ITfoxtec.Identity.Saml2#57]
Hi. The documentation says that .net classic 4.6.2+ and dotnet core are supported. But in the examples the Identity Provider is always on .net core. 
There are no limitation to implement Idp on .net classic?

**Comment by Revsgaard** [comment]
It is possible also possible to implement the IdP in .NET Framework, but you are right there is not an example. You can probably implement it by looking at https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/tree/master/test/TestIdPCore and https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/tree/master/test/TestWebAppCoreFramework and compare the code..
