### ISSUE TITLE
Support AccessDeniedPath

### ISSUE THREAD

**Issue by hnnweb** [ITfoxtec/ITfoxtec.Identity.Saml2#58]
When using [Claims-based authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/claims?view=aspnetcore-3.1) you will get redirected to `/Account/AccessDenied`

Checking the source code, it seems quite trivial to add:
in src/ITfoxtec.Identity.Saml2.MvcCore/Configuration/Saml2ServiceCollectionExtensions.cs just add another parameter to AddSaml2 and o.AccessDeniedPath = "/Login/Denied"; to the AddCookie scheme.

If it is this simple, i can add an pull-request with this change.

**Comment by Revsgaard** [comment]
Thank you for contributing

I have added support for access denied redirection target in https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/commit/f81ac9d718a9c22b3a2c611cb231107d7d8452bd
