### ISSUE TITLE
xsd mismatch for IdPSsoDescriptor

### ISSUE THREAD

**Issue by lazudrk** [ITfoxtec/ITfoxtec.Identity.Saml2#6]
Hi,
Metadata for IdP generated  does not validate against XSD schema.

I have found that the IEnumerable<Object> returned by GetXContent returned the sequence for the XML document in wrong order (as far as I Know). It returned SingleSignOnServices, SingleLogoutServices and NameIDFormats, but the correct sequence should be SingleLogoutServices , NameIDFormats, SingleSignOnServices.

I have found that, meanwhile validating against https://www.samltool.com/validate_xml.php, and if I change the order in the output xml, it validates.

Maybe I am doing somethig wrong, but nor the samltool neither other systems could validate metadata in the order obtained.

Any Clue or work arraound without edit your code?

**Comment by lazudrk** [comment]
BTW I Visual check https://docs.oasis-open.org/security/saml/v2.0/saml-schema-metadata-2.0.xsd, and the sequence for SSODescriptor and IdPSSODescriptor put the sequence in that order.

Thanks in advanced

**Comment by Revsgaard** [comment]
Thank you for the description. The bug is resolved.
https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/commit/80328ec24198138b12fe76ffee6fa6cc7167b110
