### ISSUE TITLE
Support dynamic configuration

### ISSUE THREAD

**Issue by yamaritta** [ITfoxtec/ITfoxtec.Identity.Saml2#60]
Hi.

Is it possible to add dynamic configuration at runtime with AuthenticationHandler?

for example https://github.com/dotnet/aspnetcore/tree/master/src/Security/samples/DynamicSchemes

and example di registration for OpenIdConnect 
https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectExtensions.cs

**Comment by Revsgaard** [comment]
Hi,

Yes it would probably be possible. You are welcome to make a pull request with the suggested functionality and I'll look into the code.

Best regards, Anders

**Comment by Revsgaard** [comment]
This thread has been inactive for awhile, therefore I have closed the issue.
