### ISSUE TITLE
Error in parsing XML signature returned

### ISSUE THREAD

**Issue by QinPD** [ITfoxtec/ITfoxtec.Identity.Saml2#66]
ID4037: The key needed to verify the signature could not be resolved from the following security key identifier 'SecurityKeyIdentifier
    (
    IsReadOnly = False,
    Count = 1,
    Clause[0] = System.IdentityModel.Tokens.Saml2SecurityKeyIdentifierClause
    )
'. Ensure that the SecurityTokenResolver is populated with the required key.

**Comment by Revsgaard** [comment]
Please ask the question or questions on Stackoverflow and tag the question with 'itfoxtec-identity-saml2'. And I will answer :)

I'll close the issue.
