### ISSUE TITLE
Support for aes 128 algorithm?

### ISSUE THREAD

**Issue by jgestrada** [ITfoxtec/ITfoxtec.Identity.Saml2#68]

**Comment by Revsgaard** [comment]
I do not think AES is the best solution for SAML 2.0 integration because it is a symmetric algorithm. There can of cause be use cases, but I have never had the need for AES myself. 
Therefore, I do not want to spend time on implementing AES.

**Comment by jgestrada** [comment]
thanks for your answer, i'm learning a little about this topic
