### ISSUE TITLE
Prohibited DTD in XML document

### ISSUE THREAD

**Issue by adamsulimadolina** [ITfoxtec/ITfoxtec.Identity.Saml2#73]
Hi, I'm trying to implement SAML2, but I encountered this error:

`XmlException: For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.`

in line:

`entityDescriptor.ReadIdPSsoDescriptorFromUrl(new Uri(Configuration["Saml2:IdPMetadata"]));`

Actually I don't know how to handle this, because I think it's library side error.

Thanks in advance.

**Comment by Revsgaard** [comment]
I can see you closed the issues and therefore i reckon you made it work.

**Comment by Mateusz19021996** [comment]
Hi, someone know how to resolve it?

**Comment by Mateusz19021996** [comment]
@adamsulimadolina Hi, could You tell what You did to make it works?

**Comment by Revsgaard** [comment]
Answer on Sackoverflow https://stackoverflow.com/questions/70130926/problem-with-dtd-error-some-xml-method-does-not-work

**Comment by ashokkgarg** [comment]
Make sure the path to your metadata url is correct. You can verify that by navigating to the url in browser and getting back the results containing your metadata.

**Comment by Revsgaard** [comment]
Thank you for responding, I have added the comment on stackoverflow as well.
