### ISSUE TITLE
Multiple contactpersons in Metadata

### ISSUE THREAD

**Issue by hnnweb** [ITfoxtec/ITfoxtec.Identity.Saml2#74]
To set both technical, support and administrative contact in metadata.

**Comment by Revsgaard** [comment]
It is a good idea, I'll consider how to adding support for multiple contact persons.

**Comment by Revsgaard** [comment]
I have added [metadata support for multiple contact persons](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/commit/1e8cdab549d5b4d25e113fdab297d6c37b300ca1). It will be part of the next release.
