### ISSUE TITLE
Cookies Store to Radis 

### ISSUE THREAD

**Issue by dthayyil** [ITfoxtec/ITfoxtec.Identity.Saml2#76]
Is there any way to keep the cookie to Redis, If the pod is destroyed the session will not be there so any solution?

**Comment by Revsgaard** [comment]
Yes, it is possible. I'm trying collect support on stackoverflow. Therefore, please ask the question on stackoverflow and tag it with 'itfoxtec-identity-saml2'. I'll then receive a notification email and answer your question on stackoverflow.

**Comment by Revsgaard** [comment]
On https://stackoverflow.com/questions/66691391/saml-2-sso-auth-cookie-id-move-to-distributed-with-itfoxtec-identity-saml2
