### ISSUE TITLE
How to load saml configuration in controller method

### ISSUE THREAD

**Issue by Freelancingonupwork** [ITfoxtec/ITfoxtec.Identity.Saml2#77]
HI'

I trying to load saml configuration from controller methods instead of the application startup. because I need to load the dynamic configuration based on URL parameter from the database 

Can you please let me know how can I achieve this?

thanks

**Comment by Revsgaard** [comment]
Please see https://stackoverflow.com/questions/66650741/load-saml2-configuration-on-the-runtime-instead-of-loading-it-on-the-startup
