### ISSUE TITLE
Multiple AssertionConsumerService elements in metadata

### ISSUE THREAD

**Issue by Zyano** [ITfoxtec/ITfoxtec.Identity.Saml2#81]
Hi,

While doing some work in relation to using multple AssertionConsumerServices for a single SP I noticed the metadata generates all endpoints as "default".

1.
`<m:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://test.domian.com/ContextHandlerAuth/AssertionConsumerService" index="0" isDefault="true"/>`

2. 
`<m:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://pretest.domain.com/ContextHandlerAuth/AssertionConsumerService" index="1" isDefault="true"/>`

The library currently doesn't allow for specificing the isDefault value when creating the `ITfoxtec.Identity.Saml2.Schemas.Metadata.AssertionConsumerService`

However adding this functionality would be a breaking change assuming there are people expecting this value to be true for all endpoints.

Beset regards
Stefan

**Comment by Revsgaard** [comment]
Thank you. I have made the [IsDefault attribute configurable](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/commit/6f1375e61a4a0e80fcc1c9ee4a5bbe74de20774e), do you think this will work for you?

**Comment by Zyano** [comment]
Hey, that will most definitely do the job :) Thank you.

On a side note I looked into the Saml2 Conditions on assertions and it appears the MS security token creation takes care of validating the response from an IdP. I dug into the source code MS made and it does handle conditions acoording to the saml2 spec wich again looks to be inline witth what is expected by OIOSAML.

**Comment by Revsgaard** [comment]
I have released version [4.6.1-beta1 ](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/releases/tag/4.6.1-beta1) with the new functionality.
