### ISSUE TITLE
Different CanonicalizationMethods in single SAMLResponse

### ISSUE THREAD

**Issue by feitzi** [ITfoxtec/ITfoxtec.Identity.Saml2#84]
We have the problem that our IDP is using different CanonicalizationMethods inside the same SamlResponse. There are two signatatures, one with  REC-xml-c14n-20010315 and the other with xml-exc-c14n.
The problem is that ITfoxtec.Identity.Saml2  verifies in CheckSignature() that the given CanonicalizationMethod is the same as configured. But everything should fine if the IDP CanonicalizationMethod is another than that one who is configured.

Is it required to check the CanonicalizationMethod in CheckSignature (Saml2SignedXml)? 
I will create a pull request with a possible solution to discuss.

**Comment by Revsgaard** [comment]
I do not think it is safe to remove the CanonicalizationMethod check. Instead, I think you should ask the IdP to use the same CanonicalizationMethod if the AuthnResponse is signed twice. Or ask the IdP to only sign the AuthnResponse one time either at message level or assertion level.

**Comment by feitzi** [comment]
But is signing it twice with different CanonicalizationMethod allowed, according to the SAML standard or not?
