### ISSUE TITLE
Lack of documentation explaining implementation with a 3rd party Identity Provider 

### ISSUE THREAD

**Issue by SteveRogers-Enghouse** [ITfoxtec/ITfoxtec.Identity.Saml2#86]
I have been trying to test the **TestWebApp** with the intention of trying this with an evaluation OKTA account.

I am only currently interested in creating a asp.net service provider which will use OKTA as its SAML2 Identity Provider and use **SingleSignOnDestination** pointing at the OKTA hosted logon url.  

- So I need to create a Service Provider in ASP.NET initiating the SAML2 logon on the Identity Provider.
- If I can get this working I would then look to test it on some other Identity Providers

I have loaded the solution in Visual Studio 2019 and have kept the projects under the src directory and removed all of the web projects under the test folder except for the **TestWebApp** project.  I have fixed all references and can build the project.

However, I cannot work out the configuration changes that I will need to make to connect to OKTA.  Which I checked using SAML2 against an application written in ASP.NET Core and using ITfoxtec.Identity.Saml2 (4.6.3) and ITfoxtec.Identity.Saml2.MvcCore (4.6.3)
- https://developer.okta.com/blog/2020/10/23/how-to-authenticate-with-saml-in-aspnet-core-and-csharp
- But the application that I wish to add SAML SSO to is huge and written in asp.net and I would want to apply it to a master page template rather than individually to thousands of individual pages.

Do the supplied config settings for **TestWebApp** rely upon another project also being run? 

`    <add key="Saml2:IdPMetadata" value="https://localhost:44305/metadata" />`

Looks to me that it is using a locally hosted Identity Provider. especially since the **TestWebApp** project uses https://localhost:44327/

So can I change that to use OKTA as an Identity Provider

`    <add key="Saml2:IdPMetadata" value="https://_{domain}_.okta.com/app/_{xxxxxx}_/sso/saml/metadata" />`

And change

```
    <add key="Saml2:Issuer" value="urn:itfoxtec:identity:saml2:testwebapp" />
    <add key="Saml2:SingleSignOnDestination" value="https://test-adfs.itfoxtec.com/adfs/ls/" />
    <add key="Saml2:SingleLogoutDestination" value="https://test-adfs.itfoxtec.com/adfs/ls/" />
```

To

```
    <add key="Saml2:Issuer" value="Okta_SAML_Example" />
    <add key="Saml2:SingleSignOnDestination" value="https://_{domain}_.okta.com/home/_{domain}__oktasamlexample_1/_{yyyyyyyy}_/_{zzzzzzzzzz}_/" />
    <add key="Saml2:SingleLogoutDestination" value="https://_{domain}_.okta.com/home/_{domain}__oktasamlexample_1/_{yyyyyyyy}_/_{zzzzzzzzzz}_/" />
```

It is possible to download a .cert from OKTA for the application, but I don't know how to encrypt that.
Are the following settings needed?

```
    <add key="Saml2:SigningCertificateFile" value="~/App_Data/itfoxtec.identity.saml2.testwebapp_Certificate.pfx" />
    <add key="Saml2:SigningCertificatePassword" value="!QAZ2wsx" />
```

    
Presumably the certificate needs to match the Application that has been registered with OKTA

```
    <add key="Saml2:SigningCertificateFile" value="~/App_Data/okta.cert" />
    <add key="Saml2:SigningCertificatePassword" value="Code changed to ignore this" />

```  
Can I use the OKTA downloaded certificate without a password?
    in the IdentityConfig class in the RegisterIdentity() method by just changing ...

`    Saml2Configuration.SigningCertificate = CertificateUtil.Load(HttpContext.Current.Server.MapPath(ConfigurationManager.AppSettings["Saml2:SigningCertificateFile"]), ConfigurationManager.AppSettings["Saml2:SigningCertificatePassword"]);
`    
    ... to ...
    
`Saml2Configuration.SigningCertificate = CertificateUtil.Load(HttpContext.Current.Server.MapPath(ConfigurationManager.AppSettings["Saml2:SigningCertificateFile"]));    
`
    
    ... and ignore the SigningCertificatePassword

I appreciate that these questions are quite specific and normally I would hope to work through them by myself.  But, there is a lack of documentation regarding high level flow and the specific configuration requirements.  Any help would be most useful.

**Comment by SteveRogers-Enghouse** [comment]
Hi everyone,

It's been a short time, but I have been beavering away at this.
- anyway, I thought that I would share what I have found out so far so that nobody else needs to go through the pain
-- no doubt your pain will be specific to your requirement

So to re-establish what I wanted to achieve.
- just focus on the **asp.net web application** and how that works with the underlying components
- Get it doing SSO using SAML against Oktra as an Identity Provider (for now, try it out with others later)

So, I had a stab at it and found that I did not understand the configurable settings and also had to make code changes to the code to get it to work at all.
- plus got a number of error pages back trying to run it
- No criticism, I need asp.net web applications and the focus will probably be on other technologies.

Anyway here is what I found during my painful struggles.

I managed to get the Login working against Oktra after a fashion.
Gotchas in the config file were:

Saml2:Issuer value must be a uri and match oktra settings
Audience Restriction:       urn:itfoxtec:identity:saml2:Okta_SAML_Example
`	<add key="Saml2:Issuer" value="urn:itfoxtec:identity:saml2:Okta_SAML_Example" />
`

IdPMetadata needed to point at the oktra url
`	<add key="Saml2:IdPMetadata" value="https://########.okta.com/app/####################/sso/saml/metadata" />
`
Saml2:SingleSignOnDestination and Saml2:SingleLogoutDestination needed to point to the Oktra urls
```
	<add key="Saml2:SingleSignOnDestination" value="https://########.okta.com/home/########_oktasamlexample_1/####################/####################/" />
	<add key="Saml2:SingleLogoutDestination" value="https://########.okta.com/home/########_oktasamlexample_1/####################/####################/" />

```
Also needed
`	<add key="Saml2:CertificateValidationMode" value="None" />
`

Certificate work around. 
    Downloaded X509 .cert from the Oktra Application
	replace the contents of ~/App_Data/ITfoxtecRootCertificate.crt and saved it
	it then seems that I can use the same certificate file and password

Also had to fix some code in **IdentityConfig.cs**
 because it was causing an exception.
`	Saml2Configuration.SingleLogoutDestination = entityDescriptor.IdPSsoDescriptor.SingleLogoutServices.First().Location; 
`
so replaced with
```
        if (entityDescriptor.IdPSsoDescriptor.SingleLogoutServices.FirstOrDefault() != null)
        {
                Saml2Configuration.SingleLogoutDestination = entityDescriptor.IdPSsoDescriptor.SingleLogoutServices.First().Location;
        }

```
Login worked but logout did not because it failed in AuthController.cs
I had to **comment out [ValidateAntiForgeryToken]** to stop the web page displaying the error

Now it works after a fashion, if I fire up the web app in Visual Studio it opens without error.
I can use the login link and it delivers me the Okta sign in page.
I authenticate and everything is ok.  I can see the users Claims and I get my name in the Hello.

When I logout, I don't know for sure if I am actually logged out (it says that I am), but if I login again I do not get asked for credentials from the OKTRA login page
- But the display shows me as being logged in

Oktra management portal shows the logs
-  show the logins, but no logoffs. I am new to Oktra so it is possible it does not log the logoffs.

So still trying to work out what it is doing.  But, at least it's a start.

Anyway, for now at least, I would love to know what it is supposed to do (for single instance in a browser)
- Login great
- Logout great
- login again - should I expect to enter credentials? - Not getting that

The next level of tests would be around
- Login from a tab in a browser
--  verify credentials and get in
- Login from another tab
-- not be asked - just go straight in

And the logout stuff
- I currently have no faith in it at all for the moment
-- no doubt it can be understood

Anyway, I hope that this saves someone a couple of days work.

**Comment by Revsgaard** [comment]
Thank you for the info.
