### ISSUE TITLE
Saml2PostBinding - ReadSamlResponse and Unbind both call Saml2SecurityTokenHandler.DetectReplayedToken

### ISSUE THREAD

**Issue by s-d-x** [ITfoxtec/ITfoxtec.Identity.Saml2#89]
Hi,

Thank you for the great product!

I did run into one issue... In the test projects the sample code for `AssertionConsumerService` shows to call `Saml2PostBinding.ReadSamlResponse` followed by `Saml2PostBinding.Unbind`.  

This works fine, unless you have set `Saml2Configuration.DetectReplayedTokens = true;`

In that case, both of these methods call `Saml2SecurityTokenHandler.DetectReplayedToken`, which adds the token to the cache or throws an exception if it already exists.  So when `Unbind` is called, it detects the token already exists from having called `ReadSamlResponse`, and you get the exception:
ID1066: Replay has been detected for: Token: 'System.IdentityModel.Tokens.Saml2SecurityToken', Assertion.Id.Value: ...

Looking at the code it seems `Unbind` does everything `ReadSamlResponse` does, so as a workaround for now I have been skipping the call to `ReadSamlResponse` and moving the check for `saml2AuthnResponse.Status != Saml2StatusCodes.Success` to after calling `Unbind`.  Please let me know if you see any issues with this.  It does seem it would check the signature on a response that wasn't successful anyway, was that the intent of calling `ReadSamlResponse` first?

Thanks!

**Comment by Revsgaard** [comment]
Thank you. The issue is resolved in https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/commit/0c0cef05050d633f000be9399dc6a5b1a009a6da and will be part of the next release.
There is not security risk in omitting to calling ReadSamlResponse.
