### ISSUE TITLE
Saml2ClaimTypes is hardcoded for NameId,NameIdFormat,SessionIndex

### ISSUE THREAD

**Issue by karthickcse05** [ITfoxtec/ITfoxtec.Identity.Saml2#90]
I tried to send logout request to IDP using Saml2LogoutRequest . It is reading the claim value from the principal which we are passing as params . But in the code , they are reading the claim values based on the hardcoded values of itfoxtec  whereas we have our own claim name type and name id type. How to resolve this ? 
![image](https://user-images.githubusercontent.com/40426955/129453142-37118e1e-5f0d-4327-a546-21d456a64b06.png)

![image](https://user-images.githubusercontent.com/40426955/129453170-9ec247c7-6dc8-470b-a1be-96d77d348e14.png)

**Comment by Revsgaard** [comment]
Answered on stackoverflow https://stackoverflow.com/questions/68785245/saml2claimtypes-is-hardcoded-for-nameid-nameidformat-sessionindex
