### ISSUE TITLE
Update comment for lifeTime parameter in Saml2ResponseExtensions.CreateSession

### ISSUE THREAD

**Issue by VictorK1902** [ITfoxtec/ITfoxtec.Identity.Saml2#95]
According to the comment, default lifetime is 10 Hours, but the code actually reads the exp date time from Saml2AuthnResponse
https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/blob/master/src/ITfoxtec.Identity.Saml2.MvcCore/Extensions/Saml2ResponseExtensions.cs

    await httpContext.SignInAsync(Saml2Constants.AuthenticationScheme, principal, 
        new AuthenticationProperties
        {
            AllowRefresh = true,
            IsPersistent = isPersistent,
            IssuedUtc = saml2AuthnResponse.SecurityTokenValidFrom,
            ExpiresUtc = lifetime.HasValue ? DateTimeOffset.UtcNow.Add(lifetime.Value) : saml2AuthnResponse.SecurityTokenValidTo,
        });

I'd been scratching my head for a few hours not knowing why the session randomly expires way before than 10 hours from current time. It didn't help that the SAML respone I got from an external IdP set SecurityTokenValidTo to be 5 minutes from current time and my web api default clockskew is 5 minutes as well.

Supplying an actual value for lifeTime solves my problem above.

Not a huge deal but I figure this would clarify the intended use of lifeTime a lil more and avoid confusion.

**Comment by Revsgaard** [comment]
Thank you, I have corrected/improved the help text.
