### ISSUE TITLE
Saml Response validator should allow multiple 'allowedIssuer'

### ISSUE THREAD

**Issue by kertzi** [ITfoxtec/ITfoxtec.Identity.Saml2#98]
Currently only one AllowedIssuer is possible. 
But we have Idp which have multiple EntityDescriptor element in their metadata.

When we're getting response and reading it using `Saml2PostBinding.Read()`
`Saml2RequestException` is thrown and says:
`"Invalid Issuer. Actually 'https://tunnistautuminen.suomi.fi/idp1', allowed 'https://uusi.tunnistus.fi/idp1' "`

Both are valid because there is two EntityDescriptor elements in Idp metadata.

Idp metadata: [suomi.fi metadata](https://tunnistus.suomi.fi/static/metadata/idp-metadata.xml)

It would be great to get help how to resolve

**Comment by Revsgaard** [comment]
you can configure a list of AllowedIssuers on Saml2Configuration.AllowedAudienceUris https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/blob/master/src/ITfoxtec.Identity.Saml2/Configuration/Saml2Configuration.cs#L58
