### ISSUE TITLE
Prohibited DTD Error

### ISSUE THREAD

**Issue by Mateusz19021996** [ITfoxtec/ITfoxtec.Identity.Saml2#99]
Hi! 

I got error like that:
For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.

in this part of code:
services.Configure<Saml2Configuration>(Configuration.GetSection("Saml2"));

Could You please investigate?

**Comment by Revsgaard** [comment]
Related answer on Sackoverflow https://stackoverflow.com/questions/70130926/problem-with-dtd-error-some-xml-method-does-not-work
